#!/usr/bin/env python3
"""Build a cross-release md5 index for AW resources.

Aggregates per-resource md5 hashes from two sources:

1. `work/<slug>/manifest.json` with a `resources[]` array carrying
   `md5`, `index`, `type`, and `filename` per entry. The DOS-bank
   extractor (`init.py`) emits this layout for releases it can
   handle.

2. `tmp/output/<port>/resources/resource-0x<index>.bin` files
   (parallel scratch tree, AWVM_Tools-style). md5s are computed
   on demand. Resource type is unknown from filename alone;
   recorded as None.

Output: a Markdown report listing every md5 that appears in two
or more (release, resource_index) tuples. Useful for spotting
shared assets across ports — the seed of genealogy work.

Usage:
  python3 tools/cross_release_md5_index.py [--out PATH]
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path("/home/fsanches/compartilhado/another-world-archaeology")
WORK_DIR = REPO_ROOT / "work"
TMP_OUTPUT_DIR = REPO_ROOT / "tmp" / "output"

RE_RESOURCE_FILE = re.compile(r"^resource-0x([0-9a-fA-F]+)\.bin$")


def md5_of(path: Path) -> str:
    h = hashlib.md5()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def load_work_releases() -> dict[str, list[dict]]:
    """release-slug → list of resource records.

    Each record: {index, md5, type, filename, source}.
    """
    out: dict[str, list[dict]] = {}
    for manifest_path in sorted(WORK_DIR.glob("*/manifest.json")):
        try:
            data = json.loads(manifest_path.read_text())
        except (OSError, json.JSONDecodeError):
            continue
        resources = data.get("resources")
        if not resources:
            continue
        slug = data.get("slug") or manifest_path.parent.name
        records = []
        for r in resources:
            md5 = r.get("md5")
            if not md5:
                continue
            records.append(
                {
                    "index": r.get("index"),
                    "md5": md5,
                    "type": r.get("type"),
                    "filename": r.get("filename"),
                    "source": f"work/{manifest_path.parent.name}/manifest",
                }
            )
        if records:
            out[slug] = records
    return out


def load_tmp_output_releases() -> dict[str, list[dict]]:
    """port → list of resource records (computed md5s)."""
    out: dict[str, list[dict]] = {}
    if not TMP_OUTPUT_DIR.exists():
        return out
    for port_dir in sorted(TMP_OUTPUT_DIR.iterdir()):
        res_dir = port_dir / "resources"
        if not res_dir.is_dir():
            continue
        records = []
        for f in sorted(res_dir.glob("resource-*.bin")):
            m = RE_RESOURCE_FILE.match(f.name)
            if not m:
                continue
            idx = int(m.group(1), 16)
            records.append(
                {
                    "index": idx,
                    "md5": md5_of(f),
                    "type": None,
                    "filename": f.name,
                    "source": f"tmp/output/{port_dir.name}",
                }
            )
        if records:
            out[port_dir.name] = records
    return out


def build_md5_index(
    releases: dict[str, list[dict]],
) -> dict[str, list[tuple[str, dict]]]:
    """md5 → list of (release-key, record)."""
    idx: dict[str, list[tuple[str, dict]]] = defaultdict(list)
    for release, records in releases.items():
        for r in records:
            idx[r["md5"]].append((release, r))
    return idx


def md5_intersection_table(
    md5_idx: dict[str, list[tuple[str, dict]]],
) -> dict[tuple[str, str], int]:
    """For each unordered pair of releases, count shared md5s."""
    pair_counts: dict[tuple[str, str], int] = defaultdict(int)
    for md5, entries in md5_idx.items():
        # An md5 may appear twice in the SAME release at different
        # indices (rare but possible — e.g., two empty resources).
        # Use a per-md5 set of releases for pair-counting.
        releases_with = sorted({e[0] for e in entries})
        for i in range(len(releases_with)):
            for j in range(i + 1, len(releases_with)):
                pair_counts[(releases_with[i], releases_with[j])] += 1
    return pair_counts


def render_report(
    md5_idx: dict[str, list[tuple[str, dict]]],
    releases: dict[str, list[dict]],
) -> str:
    lines: list[str] = []
    lines.append("# Cross-release md5 index of extracted resources")
    lines.append("")
    lines.append(
        "Auto-generated by `tools/cross_release_md5_index.py`. "
        "For each per-resource md5 that appears in two or more "
        "(release, resource_index) entries, this report lists the "
        "matches. Useful for spotting assets shared verbatim across "
        "ports — the starting point of genealogy investigations."
    )
    lines.append("")

    total_md5s = len(md5_idx)
    shared_md5s = [m for m, e in md5_idx.items() if len({x[0] for x in e}) >= 2]
    lines.append(f"- **Releases indexed**: {len(releases)}")
    lines.append(
        f"- **Total resources indexed**: {sum(len(v) for v in releases.values())}"
    )
    lines.append(f"- **Distinct md5s**: {total_md5s}")
    lines.append(f"- **md5s shared across ≥2 releases**: {len(shared_md5s)}")
    lines.append("")

    lines.append("## Per-release coverage")
    lines.append("")
    lines.append("| Release | Resources | Source |")
    lines.append("| --- | ---: | --- |")
    for release, records in sorted(releases.items()):
        sources = sorted({r["source"] for r in records})
        lines.append(
            f"| `{release}` | {len(records)} | "
            f"{', '.join(sources)} |"
        )
    lines.append("")

    pair_counts = md5_intersection_table(md5_idx)
    if pair_counts:
        lines.append("## Pairwise overlap (shared distinct md5s)")
        lines.append("")
        lines.append(
            "Counts UNIQUE md5s shared between each release pair, "
            "not resource-instance overlaps. Within a single release, "
            "multiple empty resources collapse to the same md5 "
            "(`d41d8cd9...`); they're counted once per pair."
        )
        lines.append("")
        lines.append("| Release A | Release B | Shared md5s |")
        lines.append("| --- | --- | ---: |")
        for (a, b), n in sorted(
            pair_counts.items(), key=lambda kv: (-kv[1], kv[0])
        ):
            lines.append(f"| `{a}` | `{b}` | {n} |")
        lines.append("")

    # Per-index diff matrix between release pairs (only when both
    # releases cover the same index space — i.e., share enough
    # indices to make a row-by-row comparison meaningful).
    index_sets = {r: {rec["index"] for rec in recs} for r, recs in releases.items()}
    sorted_releases = sorted(releases.keys())
    pairs_with_index_data = [
        (a, b)
        for i, a in enumerate(sorted_releases)
        for b in sorted_releases[i + 1 :]
        if index_sets[a] and index_sets[b]
    ]
    if pairs_with_index_data:
        lines.append("## Per-index byte-match matrix")
        lines.append("")
        lines.append(
            "For each release pair, splits resources by index status: "
            "shared-and-identical, shared-but-divergent, A-only, B-only. "
            "Type counts are listed for shared-but-divergent — these are "
            "the resources where re-encoding (vs. simple reuse) happened."
        )
        lines.append("")
        lines.append(
            "| Release A | Release B | Same idx + same md5 | "
            "Same idx + diff md5 | A-only | B-only | "
            "Diff types |"
        )
        lines.append(
            "| --- | --- | ---: | ---: | ---: | ---: | --- |"
        )
        per_release_idx_md5 = {
            r: {rec["index"]: (rec["md5"], rec.get("type")) for rec in recs}
            for r, recs in releases.items()
        }
        for a, b in pairs_with_index_data:
            ai = per_release_idx_md5[a]
            bi = per_release_idx_md5[b]
            shared = sorted(set(ai.keys()) & set(bi.keys()))
            same_md5 = sum(1 for i in shared if ai[i][0] == bi[i][0])
            # For type inference, fall back to ANY release that has
            # type metadata for this index (not just the two being
            # paired). This way amiga↔msdos rows can borrow types from
            # the dos manifest.
            type_by_idx = {}
            for rel_recs in releases.values():
                for rec in rel_recs:
                    if rec.get("type") and rec["index"] not in type_by_idx:
                        type_by_idx[rec["index"]] = rec["type"]
            diff_md5 = []
            for i in shared:
                if ai[i][0] != bi[i][0]:
                    diff_md5.append((i, type_by_idx.get(i, "?")))
            a_only = len(set(ai.keys()) - set(bi.keys()))
            b_only = len(set(bi.keys()) - set(ai.keys()))
            from collections import Counter
            type_counts = Counter(t for _, t in diff_md5)
            type_str = ", ".join(
                f"{t}:{c}" for t, c in sorted(type_counts.items())
            ) or "—"
            lines.append(
                f"| `{a}` | `{b}` | {same_md5} | {len(diff_md5)} | "
                f"{a_only} | {b_only} | {type_str} |"
            )
        lines.append("")

    # Per-port origin classification (lineage analysis).
    # For each non-reference port, classify each of its resources by
    # which of {amiga, dos} it byte-matches at the same index.
    # The "matches dos only, NOT amiga" column is the smoking gun for
    # DOS-derived ports (Mac); zero values mean Amiga-derived (Atari).
    if "amiga" in releases and ("dos" in releases or "msdos" in releases):
        ref_amiga = {rec["index"]: rec["md5"] for rec in releases["amiga"]}
        dos_release = "dos" if "dos" in releases else "msdos"
        ref_dos = {rec["index"]: rec["md5"] for rec in releases[dos_release]}

        non_ref_ports = [
            r for r in sorted(releases) if r not in {"amiga", dos_release, "msdos"}
        ]
        if non_ref_ports:
            lines.append("## Per-port origin classification (lineage analysis)")
            lines.append("")
            lines.append(
                "For each non-reference port, classifies its resources by "
                f"whether they byte-match `amiga` and/or `{dos_release}` at "
                "the same index. The lineage signal is in **`matches DOS "
                "only`**: non-zero means the port inherited DOS-rebuilt "
                "resources; zero rules out a DOS→port arrow."
            )
            lines.append("")
            lines.append(
                "| Port | total | both | amiga only | DOS only | unique | inferred lineage |"
            )
            lines.append("| --- | ---: | ---: | ---: | ---: | ---: | --- |")
            for port in non_ref_ports:
                port_idx_md5 = {rec["index"]: rec["md5"] for rec in releases[port]}
                total = len(port_idx_md5)
                both = amiga_only = dos_only = unique = 0
                for idx, md5 in port_idx_md5.items():
                    a = ref_amiga.get(idx) == md5
                    d = ref_dos.get(idx) == md5
                    if a and d:
                        both += 1
                    elif a:
                        amiga_only += 1
                    elif d:
                        dos_only += 1
                    else:
                        unique += 1
                # Infer lineage hint
                if dos_only > 0 and amiga_only == 0:
                    lineage = "**DOS-derived**"
                elif amiga_only > 0 and dos_only == 0:
                    lineage = "**Chahi 1991 sibling**"
                elif amiga_only == 0 and dos_only == 0 and both > 0:
                    lineage = "ambiguous (only shared resources)"
                elif amiga_only == 0 and dos_only == 0 and both == 0:
                    lineage = "no overlap (independent rebuild)"
                else:
                    lineage = "mixed"
                lines.append(
                    f"| `{port}` | {total} | {both} | {amiga_only} | "
                    f"{dos_only} | {unique} | {lineage} |"
                )
            lines.append("")

    if shared_md5s:
        lines.append("## Shared md5 catalog")
        lines.append("")
        lines.append(
            "Each entry: md5 → list of `(release, index, type, filename)` "
            "matches. Sorted by descending match-count, then by md5."
        )
        lines.append("")

        def sort_key(md5: str) -> tuple[int, str]:
            count = len({x[0] for x in md5_idx[md5]})
            return (-count, md5)

        for md5 in sorted(shared_md5s, key=sort_key):
            entries = md5_idx[md5]
            n_releases = len({e[0] for e in entries})
            lines.append(f"### `{md5}` ({n_releases} releases)")
            lines.append("")
            for release, rec in sorted(
                entries, key=lambda er: (er[0], er[1].get("index") or 0)
            ):
                idx = rec.get("index")
                idx_str = (
                    f"0x{idx:02x}"
                    if isinstance(idx, int)
                    else (rec.get("filename") or "?")
                )
                rtype = rec.get("type") or "?"
                fname = rec.get("filename") or ""
                lines.append(
                    f"- `{release}` index={idx_str} type={rtype} "
                    f"file=`{fname}`"
                )
            lines.append("")

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--out",
        type=Path,
        default=REPO_ROOT / "docs" / "cross-release-md5-index.md",
    )
    args = parser.parse_args()

    work_releases = load_work_releases()
    tmp_releases = load_tmp_output_releases()
    releases = {**work_releases, **tmp_releases}

    if not releases:
        print(
            "no releases with per-resource md5 data found; "
            "nothing to index",
            file=sys.stderr,
        )
        return 1

    md5_idx = build_md5_index(releases)
    report = render_report(md5_idx, releases)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(report)
    print(
        f"wrote {args.out} "
        f"({len(releases)} releases, "
        f"{sum(len(v) for v in releases.values())} resources, "
        f"{len(md5_idx)} distinct md5s)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
