#!/usr/bin/env python3
"""Snapshot the load-bearing `;@raw=` residue.

For each per-branch `.asm` file that still needs `;@raw=`
annotations, capture the byte-level pattern of where the encoder
disagrees with the original. The output is a Markdown reference
reviewers can read to see *what kinds of encoder gaps still exist*
without having to rerun the audit themselves.

Output: `docs/raw_annotation_load_bearing.md`.

Method:
  1. Assemble file as-is (baseline).
  2. Strip all `;@raw=` and assemble (stripped).
  3. Diff. Group adjacent diff bytes into runs.
  4. Tally `(baseline_byte, stripped_byte)` pairs across runs:
     these expose the encoder's mistake patterns directly.
"""
from __future__ import annotations

import re
import subprocess
import sys
import tempfile
from collections import Counter
from pathlib import Path

from _paths import AWVM_ASM, AW_SRC, REPO_ROOT

SRC_ROOT = AW_SRC

sys.path.insert(0, str(REPO_ROOT / "tools"))

RE_RAW = re.compile(r"\s*;@raw=([0-9a-fA-FxX,\s]+)\s*$")


def expand_text(asm_path: Path) -> str:
    from awvm_preprocess import expand_includes, expand_fill_macros
    text = expand_includes(asm_path.read_text(), asm_path.resolve().parent)
    text = expand_fill_macros(text)
    return text


def assemble_text(text: str, hint: str) -> bytes:
    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        f = td / f"{hint}.asm"
        f.write_text(text)
        subprocess.run(
            [str(AWVM_ASM), f.name],
            cwd=td,
            check=True,
            capture_output=True,
            text=True,
        )
        return f.with_suffix(".bin").read_bytes()


def strip_text(text: str) -> str:
    out = []
    for line in text.splitlines(keepends=True):
        m = RE_RAW.search(line)
        if not m:
            out.append(line)
            continue
        new = line[: m.start()].rstrip()
        if line.endswith("\n"):
            new += "\n"
        out.append(new)
    return "".join(out)


def collect_diff_runs(
    a: bytes, b: bytes
) -> list[tuple[int, bytes, bytes]]:
    """Return list of (offset, baseline_run, stripped_run) for each
    contiguous diff region."""
    n = min(len(a), len(b))
    runs: list[tuple[int, list[int], list[int]]] = []
    cur: list[int] | None = None
    cur_a: list[int] = []
    cur_b: list[int] = []
    for i in range(n):
        if a[i] != b[i]:
            if cur is None:
                cur = i
                cur_a = []
                cur_b = []
            cur_a.append(a[i])
            cur_b.append(b[i])
        else:
            if cur is not None:
                runs.append((cur, cur_a, cur_b))
                cur = None
    if cur is not None:
        runs.append((cur, cur_a, cur_b))
    return [(o, bytes(ba), bytes(bb)) for o, ba, bb in runs]


def main() -> int:
    out_path = REPO_ROOT / "docs" / "raw_annotation_load_bearing.md"

    files: list[Path] = []
    for branch_dir in sorted((SRC_ROOT / "src" / "levels").iterdir()):
        if not branch_dir.is_dir() or branch_dir.name.startswith("_"):
            continue
        files.extend(sorted(branch_dir.glob("*.asm")))

    md: list[str] = []
    md.append("# `;@raw=` load-bearing residue snapshot")
    md.append("")
    md.append(
        "Auto-generated by `tools/raw_annotation_snapshot.py`. For "
        "each per-branch `.asm` file, this report captures the byte-"
        "level pattern of where stripping every `;@raw=` annotation "
        "and re-assembling produces a *different* output than the "
        "annotated baseline. The (baseline, stripped) byte pairs are "
        "the fingerprint of the encoder's gaps — they tell awvm-asm's "
        "maintainer exactly which opcodes / operand-shapes still need "
        "encoder fixes."
    )
    md.append("")

    file_summaries: list[dict] = []
    pair_tally: Counter = Counter()  # (baseline_byte, stripped_byte) -> count

    for asm_path in files:
        text = expand_text(asm_path)
        try:
            baseline = assemble_text(text, asm_path.stem + "_b")
        except subprocess.CalledProcessError:
            continue
        try:
            stripped = assemble_text(strip_text(text), asm_path.stem + "_s")
        except subprocess.CalledProcessError:
            stripped = None

        if stripped is None or baseline == stripped:
            file_summaries.append(
                {
                    "file": str(asm_path.relative_to(SRC_ROOT)),
                    "diff_bytes": 0 if stripped is not None else "stripped_failed",
                    "runs": [],
                }
            )
            continue

        runs = collect_diff_runs(baseline, stripped)
        diff_bytes = sum(len(ba) for _, ba, _ in runs)
        for _, ba, bb in runs:
            for x, y in zip(ba, bb):
                pair_tally[(x, y)] += 1
        file_summaries.append(
            {
                "file": str(asm_path.relative_to(SRC_ROOT)),
                "diff_bytes": diff_bytes,
                "runs": runs[:8],  # cap at 8 sample runs per file
            }
        )

    md.append("## Per-file load-bearing summary")
    md.append("")
    md.append("| File | Load-bearing bytes |")
    md.append("| --- | ---: |")
    for s in file_summaries:
        md.append(f"| `{s['file']}` | {s['diff_bytes']} |")
    md.append("")

    md.append("## Encoder mistake fingerprint (top byte-pair patterns)")
    md.append("")
    md.append(
        "Each row: when the encoder is asked to encode the original "
        "instruction *without* its `;@raw=` annotation, it emits "
        "`stripped` where the original (baseline) had `baseline`. The "
        "1-bit deltas typically point to a specific opcode-flag the "
        "encoder isn't toggling correctly. A small handful of patterns "
        "dominate: an `xor=0x03` shift in the `0x55..0x7F` range is "
        "the encoder's mis-handling of bits 0-1 of the video opcode "
        "(zoom-encoding mode flag). Fixing that single pattern is "
        "expected to retire the bulk of the residue."
    )
    md.append("")
    md.append("| baseline | stripped | xor | count |")
    md.append("| ---: | ---: | ---: | ---: |")
    for (b, s), n in pair_tally.most_common(40):
        md.append(
            f"| `0x{b:02x}` | `0x{s:02x}` | `0x{b ^ s:02x}` | {n} |"
        )
    md.append("")

    md.append("## Per-file diff samples")
    md.append("")
    md.append(
        "First few load-bearing runs from each file with mismatches. "
        "Use the offset to locate the source line; the byte-pair tells "
        "you which encoder branch needs work."
    )
    md.append("")
    for s in file_summaries:
        if not s["runs"]:
            continue
        md.append(f"### `{s['file']}`")
        md.append("")
        md.append("| offset | baseline | stripped |")
        md.append("| --- | --- | --- |")
        for off, ba, bb in s["runs"]:
            md.append(
                f"| 0x{off:04x} | `{ba.hex()}` | `{bb.hex()}` |"
            )
        md.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(md) + "\n")
    print(f"wrote {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
