#!/usr/bin/env python3
"""Strip unreferenced LABEL_<HEX> definitions from unified chunk files.

A label is "unreferenced" if its name appears EXACTLY ONCE across the
entire `src/levels/` tree (the def line itself). Such labels add
visual noise but contribute zero bytes to the assembler's output —
the assembler only resolves names that are actually used as
operands, so stripping them is byte-neutral.

Safety net: this tool only strips labels in the unified chunks
(`src/levels/_unified/<stage>/<...>.inc`). Per-port files
(`src/levels/<branch>/<STAGE>.asm`) are autogenerated by
AnotherWorld_VMTools' disassembler and should not be hand-edited;
they're left alone.

Usage:
    python3 tools/strip_unreferenced_labels.py <src-tree-root>

Where `<src-tree-root>` is the source-reconstruction repo root
(the parent of `src/levels/`).
"""
from __future__ import annotations
import re
import sys
from pathlib import Path
from collections import defaultdict


LABEL_TOKEN = re.compile(r'\bLABEL_[0-9A-F]{4}\b')
LABEL_DEF_LINE = re.compile(r'^(LABEL_[0-9A-F]{4}):\s*(?:;.*)?$')


def main(roots: list[str]) -> int:
    if not roots:
        print("usage: strip_unreferenced_labels.py <src-recon-root>", file=sys.stderr)
        return 2

    levels_root = Path(roots[0]) / "src" / "levels"
    if not levels_root.is_dir():
        print(f"not a source-recon root: {roots[0]} (no src/levels/)", file=sys.stderr)
        return 2

    # 1. Count occurrences of every LABEL_HEX token across the WHOLE
    #    src/levels/ tree (per-port .asm + unified .asm.in + chunks).
    occurrences: dict[str, int] = defaultdict(int)
    for path in levels_root.rglob("*"):
        if not path.is_file():
            continue
        if path.suffix not in {".asm", ".inc", ".in"}:
            continue
        try:
            text = path.read_text()
        except (UnicodeDecodeError, OSError):
            continue
        for tok in LABEL_TOKEN.findall(text):
            occurrences[tok] += 1

    unreferenced = {tok for tok, n in occurrences.items() if n == 1}
    print(f"Total LABEL_HEX tokens: {len(occurrences)}")
    print(f"Singleton (defined once, never referenced): {len(unreferenced)}")

    if not unreferenced:
        return 0

    # 2. For each unified chunk file, strip lines that are def-only and
    #    whose label is in the unreferenced set.
    unified_root = levels_root / "_unified"
    files_changed = 0
    lines_dropped = 0

    for path in unified_root.rglob("*.inc"):
        try:
            text = path.read_text()
        except (UnicodeDecodeError, OSError):
            continue

        new_lines = []
        local_dropped = 0
        for line in text.splitlines():
            m = LABEL_DEF_LINE.match(line)
            if m and m.group(1) in unreferenced:
                local_dropped += 1
                continue
            new_lines.append(line)

        if local_dropped:
            new_text = "\n".join(new_lines)
            if text.endswith("\n"):
                new_text += "\n"
            path.write_text(new_text)
            files_changed += 1
            lines_dropped += local_dropped

    print(f"Files changed: {files_changed}")
    print(f"Lines dropped: {lines_dropped}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
